### ISSUE TITLE
Collecting job results fails with abs path

### ISSUE THREAD

**Issue by sashayakovtseva** [sylabs/wlm-operator#22]
```
  mount:
      name: data
      hostPath:
        path: /home/vagrant/job-results
        type: DirectoryOrCreate
    from: /home/vagrant/fake.txt
```

Error: `running batch can't create file with results on mounted volume: open /collect/cow-job/home/vagrant/fake.txt: no such file or directory`
